# Generated by Django 3.0.3 on 2020-03-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='train_detail',
            fields=[
                ('train_no', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('no_of_seat', models.IntegerField()),
                ('route', models.CharField(default='', max_length=100000)),
                ('distance', models.CharField(default='', max_length=100000)),
                ('time', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('pnr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_passenger', models.IntegerField()),
                ('date', models.DateField()),
                ('train_class', models.CharField(default='', max_length=100)),
                ('departure_station', models.CharField(default='', max_length=100)),
                ('arrival_station', models.CharField(default='', max_length=100)),
                ('departure_station_rdist', models.IntegerField(default=0)),
                ('arrival_station_rdist', models.IntegerField(default=0)),
                ('train_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.train_detail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.passenger_detail')),
            ],
        ),
        migrations.CreateModel(
            name='booked_passenger_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=200)),
                ('l_name', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('pnr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.detail')),
            ],
        ),
    ]
