# Generated by Django 3.0.3 on 2020-03-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class', models.IntegerField(default=0)),
                ('second_class', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.train_detail')),
            ],
        ),
    ]
