# Generated by Django 3.0.3 on 2020-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='got_slot',
            field=models.CharField(default='', max_length=20),
        ),
    ]
