# Generated by Django 3.0.3 on 2020-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_detail',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=14)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
